; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25017.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Adam Brenn\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
